version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: raozhanping/serve:v0.0.1
    # container_name: serve
    # hostname: "note-zhanping"
    volumes:
      - /home/zhanping/workdir/myNote/_book:/app/build
    # deploy:
    #   replicas: 5
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    ports:
      - "2000:5000"
    networks:
      - webnet
networks:
  webnet: